package rental;
// Generated 25.12.2018 20:02:08 by Hibernate Tools 4.3.1

import javax.persistence.Column; 
import javax.persistence.Entity; 
import javax.persistence.Id; 
import javax.persistence.Table;

/**
 * NewUsers generated by hbm2java
 */
@Entity
@Table(name="users")
public class NewUsers  {

    @Id
    @Column(name="id")
     private int id;
    
    @Column(name="name")
     private String name;
    
    @Column(name="mail")
     private String mail;
    
    @Column(name="role")
     private String role;
    
    @Column(name="password")
     private String password;

    public NewUsers() {
    }


    public NewUsers(int id) {
        this.id = id;
    }
    public NewUsers(int id, String name, String mail, String role, String password) {
       this.id = id;
       this.name = name;
       this.mail = mail;
       this.role = role;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


